### ISSUE TITLE
generator `update_pool_rewards` need to update `proxy_reward_balance_before_update` 

### ISSUE THREAD

**Issue by YunSuk-Yeo** [astroport-fi/astroport-core#130]
Don't we need to update `pool.proxy_reward_balance_before_update` to latest `reward_amount`?

```rust
pool.proxy_reward_balance_before_update = reward_amount
```

https://github.com/astroport-fi/astroport/blob/0743c710f177d546b34296fe3c08b621711cf612/contracts/tokenomics/generator/src/contract.rs#L433-L438

I know it is not the problem now because all function executed after `update_rewards_and_execute`, and this function update `pool.proxy_reward_balance_before_update`. hmm maybe better to define some `CONTRACT` statement like this function should be executed after `update_rewards_and_execute`.

**Comment by ShadoySV** [comment]
Yes, we need, doing so we avoid double adding of latest share increase, we'll do it, thank you

**Comment by wedancedalot** [comment]
Fixed via #157
