### ISSUE TITLE
precision mismatch on spread amount calc

### ISSUE THREAD

**Issue by TheWineSeller** [astroport-fi/astroport-core#164]
https://github.com/astroport-fi/astroport-core/blob/7aa47b36d776f3aff83968aa2f64c21f67d89152/contracts/pair_stable/src/contract.rs#L1190

`offer_amount`: `greater_precision`
`return amount`: `ask_precision`

for example, If `offer_precision` = 9 and `ask_precision` = 6
`offer_amount`: 9
`return amount`: 6

**Comment by wedancedalot** [comment]
Fixed in #167
