### ISSUE TITLE
Testnet contract addresses

### ISSUE THREAD

**Issue by keith555** [astroport-fi/astroport-core#187]
Hi, I'm finding it difficult to find Astroport contract address for Testnet. Could you point me in the right direction, or consider this a request to publish them if they're not currently available? Thanks.

**Comment by wedancedalot** [comment]
Hi, you can find the latest addresses of contracts in this repo:
https://github.com/astroport-fi/astroport-changelog

**Comment by keith555** [comment]
Awesome. Thanks a lot.

**Comment by keith555** [comment]
Hi, could you tell me where I can find the testnet version for this contract? Thanks.

    terra1j66jatn3k50hjtg2xemnjm8s7y8dws9xqa5y8w: {
      dex: "astroport",
      type: "stable",
      assets: ["uluna", "terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp"],
