### ISSUE TITLE
Publish updated version to crates.io

### ISSUE THREAD

**Issue by ewoolsey** [astroport-fi/astroport-core#331]
Hey Fellas! Eric from the team over at [Neptune Finance](https://nept.finance). We're working on publishing our API to crates.io and we have some Astroport deps in our project. Do you think it would be possible to get a new version of the crate published that's compatible with all the 1.0.0 CW deps?

**Comment by ShadoySV** [comment]
Hey @ewoolsey! On which version are your packages depending? We will publish this version

**Comment by ewoolsey** [comment]
> Hey @ewoolsey! On which version are your packages depending? We will publish this version

I'm currently depending on branch `main` and that's working great. I'm mostly using msg types from `pair` and `router`

**Comment by ShadoySV** [comment]
Version `1.2.0` of `astroport` package has been uploaded

**Comment by ewoolsey** [comment]
> Version `1.2.0` of `astroport` package has been uploaded

Awesome! I've got that in my toml and everything is working A1. Thanks so much @ShadoySV.
