### ISSUE TITLE
Publish updated version to crates.io

### ISSUE THREAD

**Issue by YAKA-DEV01** [astroport-fi/astroport-core#377]
Dear Astroport team, we have some Astroport deps in our project, but we found some common types and queriers are not included in `astroport v2.8.0`. Do you think it would be possible to get a new version of the crate published which includes the latest features?

**Comment by epanchee** [comment]
Hello,

Could you clarify what kind of new features do you need?

**Comment by YAKA-DEV01** [comment]
Hey, we would like to use the [Observation](https://github.com/astroport-fi/astroport-core/blob/v3.3.2/packages/astroport/src/observation.rs) type in `v3.3.2`.

**Comment by epanchee** [comment]
This API is not yet finalized and will have a major internal redesign in a near feature. Also worth to note that none of our deployments use this feature (neither mainnets nor testnets).

If you want to start build over [this](https://github.com/astroport-fi/astroport-core/blob/db40908a6a369eed307bfb0ca24c35237316bf01/packages/astroport/src/pair.rs#L127-L129) specific pair endpoint then there shouldn't be any issues on your side after our internal redesign.

Until this feature is finalized I suggest you to use Astroport as a git cargo dependency:
```
astroport = { git = "https://github.com/astroport-fi/astroport-core", tag = "v3.3.2", version = "3" }
```

**Comment by YAKA-DEV01** [comment]
Got it. Thanks very much for your clearly reply and kindly suggestions.
