### ISSUE TITLE
Error: [reason:"insufficient funds" metadata:{key:"ABCICode" value:"5"} metadata:{key:"Codespace" value:"sdk"}]: rpc error: code = Unknown desc = spendable balance 24995000000000inj is smaller than 200000000000000inj: insufficient funds: insufficient funds [!injective!labs/cosmos-sdk@v0.47.2-inj-4/x/auth/ante/fee.go:132] With gas wanted: '50000000' and gas used: '15391' : unknown request

### ISSUE THREAD

**Issue by creazone** [astroport-fi/astroport-core#393]
Error: [reason:"insufficient funds" metadata:{key:"ABCICode" value:"5"} metadata:{key:"Codespace" value:"sdk"}]: rpc error: code = Unknown desc = spendable balance 24995000000000inj is smaller than 200000000000000inj: insufficient funds: insufficient funds [!injective!labs/cosmos-sdk@v0.47.2-inj-4/x/auth/ante/fee.go:132] With gas wanted: '50000000' and gas used: '15391' : unknown request

**Comment by creazone** [comment]
Please support

**Comment by epanchee** [comment]
Hello @creazone ,
Please report Astroport UI issues to our [support channel](https://discord.com/channels/886922190489002004/886922191155912734).
