### ISSUE TITLE
[bug] can't swap on neutron

### ISSUE THREAD

**Issue by Kwaskoff** [astroport-fi/astroport-core#399]
![Screenshot from 2024-01-07 23-49-49](https://github.com/astroport-fi/astroport-core/assets/15308024/bcd8d5fb-8e09-4f4e-9d2d-3292f175171f)
Chromium Version 120.0.6099.129 (Official Build) Fedora Project (64-bit)
Keplr 0.11.41
Ledger nano

**Comment by epanchee** [comment]
Hi @Kwaskoff !

This is well known issue and it is not related to smart contracts. Ledger Nano S has very small memory capacity and can't handle big messages. I assume your swap path in the picture was NTRN -> USDC -> ASTRO. Try reducing the number of hops (swap NTRN -> USDC and USDC -> ASTRO separately) or consider upgrading to Ledger Nano S+ or X.
