### ISSUE TITLE
What is the contract version corresponding to Neutron 33?

### ISSUE THREAD

**Issue by ong-ar** [astroport-fi/astroport-core#415]
I've compared the checksums of the released contracts, but I don't see an address like `f6e81f775b41c676907b42755dbedcafe886e777f4f607e87a75c398ba8b397e`. Even if it's a revision, I'd appreciate knowing the version.

**Comment by epanchee** [comment]
Hello @ong-ar ,

Could you clarify what is the contract you're looking for?

**Comment by ong-ar** [comment]
@epanchee 

https://docs.astroport.fi/docs/develop/smart-contracts/contract-addresses#neutron

![스크린샷 2024-04-12 오전 11 13 09](https://github.com/astroport-fi/astroport-core/assets/5284226/d42969eb-e7b8-4bed-892d-2ef46fa4e8c4)

Factory

**Comment by epanchee** [comment]
The most up to date info stored in this repo https://github.com/astroport-fi/astroport-changelog

Current Factory code id on Neutron is 698 https://neutron.celat.one/neutron-1/contracts/neutron1hptk0k5kng7hjy35vmh009qd5m6l33609nypgf2yc6nqnewduqasxplt4e

Which corresponds to binary in [v3.10 release](https://github.com/astroport-fi/astroport-core/releases/tag/v3.10.0)
