### ISSUE TITLE
cargo schema failed

### ISSUE THREAD

**Issue by ong-ar** [astroport-fi/astroport-core#417]
`v3.10.0`

There are several contracts where `cargo schema` is not working.

example path: 
`/contracts/periphery/liquidity_manager`

Are there any specific reasons?

**Comment by epanchee** [comment]
Hello @ong-ar ,

Works for me on `v3.10.0` using `cargo run --example liquidity_manager_schema`

**Comment by ong-ar** [comment]
@epanchee 

When creating a program to extract schemas, if there is no script available, there is no specific way to handle it. Is it possible to provide a common script corresponding to cargo schema as follows?

`config`

[alias]
wasm = "build --release --target wasm32-unknown-unknown"
unit-test = "test --lib"
schema = "run --example schema"

**Comment by epanchee** [comment]
Hello @ong-ar ,

All generated schemas were added here https://github.com/astroport-fi/astroport-core/tree/main/schemas
Also you can use this script to confirm that schemas are correct https://github.com/astroport-fi/astroport-core/blob/main/scripts/build_schemas.sh
